export const uk21 = {
	msg_type: 'LOAD_SETTINGS',
	params: {
		settings: {
			botSettingsBet: {
				betRuleProfit: [1, 30],
				betRuleCoef: [1, 8],
				betRuleLifetime: [0, 2],
				betRuleForksSort: 'MAX_PROFIT',
				betDelayMaxCouponOpen: 45,
				betDelayFailtureTry: 1,
				betDelaySuccessTry: 1,
				betDelaySecondLeverageMax: 30,
				betDelayNonOverlap: 0,
				betDelayTryMax: 120,
				betParamExcludeHnd: [],
				betParamExcludeTeamTotals: [],
				betParamExcludeTotals: [],
				betStakeValueBetIf2ndDisabled: false,
				skipValidation: false,
				marketsBySport: {
					soccer: {
						WIN: false,
						HALF_WIN: false,
						WIN_CORNERS: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						HALF_ASIAN_TOTALS: false,
						HALF_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						HANDICAP: false,
						HALF_HANDICAP: false,
						ASIAN_TOTALS_CORNERS: false,
						HALF_ASIAN_TOTALS_CORNERS: false,
						HALF_HANDICAP_CORNERS: false,
						HALF_TEAM_TOTALS_CORNERS: false,
						HALF_TOTALS_CORNERS: false,
						HALF_TOTALS_CORNERS_3W: false,
						HALF_WIN_CORNERS: false,
						HANDICAP_CORNERS: false,
						TEAM_TOTALS_CORNERS: false,
						TOTALS_CORNERS: false,
						TOTALS_CORNERS_3W: false,
						CORRECT_SCORE: false,
						HALF_TEAMS_TO_SCORE: false,
						HALF_TOTALS_ODD: false,
						TEAMS_TO_SCORE: false,
						TOTALS_ODD: false,
						WHO_SCORE_3W: false,
						OTHER: false,
						TEAM_GOALS: false,
						ALL_TEAMS_GOALS: false,
						HALF_ALL_TEAMS_GOALS: false,
					},
					tennis: {
						WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						GAME_WIN: false,
						SET_TOTALS_ODD: false,
						OTHER: false,
						SET_WILL_BE_OT: false,
						SET_TEAMS_TO_SCORE: false,
					},
					hockey: {
						WIN: false,
						WIN_OT: false,
						WIN_RT: false,
						SET_WIN: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						SET_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						HANDICAP_RT: false,
						HANDICAP_OT: false,
						CORRECT_SCORE: false,
						TEAMS_TO_SCORE: false,
						OTHER: false,
						TOTALS_OT: false,
						TOTALS_RT: false,
						TEAM_GOALS: false,
						SET_TEAM_GOALS: false,
						ALL_TEAMS_GOALS: false,
						SET_TEAMS_TO_SCORE: false,
						SET_ALL_TEAMS_GOALS: false,
					},
					basketball: {
						WIN: false,
						HALF_WIN: false,
						SET_WIN: false,
						WIN_OT: false,
						TOTALS: false,
						HALF_TOTALS: false,
						SET_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						HANDICAP_OT: false,
						HALF_HANDICAP: false,
						SET_HANDICAP: false,
						CORRECT_SCORE: false,
						HALF_TOTALS_ODD: false,
						SET_TOTALS_ODD: false,
						TOTALS_ODD: false,
						OTHER: false,
						TOTALS_OT: false,
						TEAM_GOALS: false,
						SET_TOTALS_3W: false,
						HALF_TOTALS_3W: false,
						SET_TEAM_GOALS: false,
						TEAM_TOTALS_OT: false,
						HALF_TEAM_GOALS: false,
					},
					baseball: {
						WIN: false,
						HALF_WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						HALF_TOTALS: false,
						HALF_TOTALS_3W: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						HALF_HANDICAP: false,
						HANDICAP_OT: false,
						CORRECT_SCORE: false,
						TOTALS_ODD: false,
						OTHER: false,
						TOTALS_OT: false,
						TEAM_GOALS: false,
						WHO_SCORE_3W: false,
						SET_TEAM_GOALS: false,
						TEAMS_TO_SCORE: false,
						TEAM_TOTALS_OT: false,
						ALL_TEAMS_GOALS: false,
						HALF_TEAM_GOALS: false,
						SET_TEAMS_TO_SCORE: false,
						HALF_TEAMS_TO_SCORE: false,
						SET_ALL_TEAMS_GOALS: false,
						HALF_ALL_TEAMS_GOALS: false,
					},
					volleyball: {
						WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						SET_TOTALS_ODD: false,
						OTHER: false,
						SET_TEAMS_TO_SCORE: false,
					},
					badminton: {
						WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						SET_TOTALS_ODD: false,
						OTHER: false,
						SET_WILL_BE_OT: false,
						SET_TEAMS_TO_SCORE: false,
					},
					futsal: {
						WIN: false,
						HALF_WIN: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						HALF_ASIAN_TOTALS: false,
						HALF_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						HANDICAP: false,
						HALF_HANDICAP: false,
					},
					handball: {
						WIN: false,
						HALF_WIN: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						HALF_ASIAN_TOTALS: false,
						HALF_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						HANDICAP: false,
						HALF_HANDICAP: false,
						CORRECT_SCORE: false,
						HALF_TOTALS_ODD: false,
						TOTALS_ODD: false,
						OTHER: false,
						TEAM_GOALS: false,
						HALF_TEAM_GOALS: false,
					},
					rugby: {
						WIN: false,
						HALF_WIN: false,
						SET_WIN: false,
						WIN_OT: false,
						TOTALS: false,
						HALF_TOTALS: false,
						SET_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						HALF_HANDICAP: false,
						SET_HANDICAP: false,
						HANDICAP_OT: false,
					},
					'esports.soccer': {
						WIN: false,
						HALF_WIN: false,
						WIN_CORNERS: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						HALF_ASIAN_TOTALS: false,
						HALF_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						HANDICAP: false,
						HALF_HANDICAP: false,
						ASIAN_TOTALS_CORNERS: false,
						HALF_ASIAN_TOTALS_CORNERS: false,
						HALF_HANDICAP_CORNERS: false,
						HALF_TEAM_TOTALS_CORNERS: false,
						HALF_TOTALS_CORNERS: false,
						HALF_TOTALS_CORNERS_3W: false,
						HALF_WIN_CORNERS: false,
						HANDICAP_CORNERS: false,
						TEAM_TOTALS_CORNERS: false,
						TOTALS_CORNERS: false,
						TOTALS_CORNERS_3W: false,
						CORRECT_SCORE: false,
						HALF_TEAMS_TO_SCORE: false,
						HALF_TOTALS_ODD: false,
						TEAMS_TO_SCORE: false,
						TOTALS_ODD: false,
						WHO_SCORE_3W: false,
						OTHER: false,
						TEAM_GOALS: false,
						ALL_TEAMS_GOALS: false,
						HALF_ALL_TEAMS_GOALS: false,
					},
					esports: {
						WIN: true,
						SET_WIN: true,
						TOTALS: true,
						SET_TOTALS: true,
						TEAM_TOTALS: true,
						SET_TEAM_TOTALS: true,
						HANDICAP: true,
						SET_HANDICAP: true,
						SET_TOTALS_ODD: false,
						OTHER: false,
					},
					'esports.cs': {
						WIN: true,
						SET_WIN: true,
						TOTALS: true,
						SET_TOTALS: true,
						TEAM_TOTALS: true,
						SET_TEAM_TOTALS: true,
						HANDICAP: true,
						SET_HANDICAP: true,
						SET_TOTALS_ODD: false,
						OTHER: false,
					},
					'esports.dota2': {
						WIN: true,
						SET_WIN: true,
						TOTALS: true,
						SET_TOTALS: true,
						TEAM_TOTALS: true,
						SET_TEAM_TOTALS: true,
						HANDICAP: true,
						SET_HANDICAP: true,
						SET_TOTALS_ODD: false,
						OTHER: false,
					},
					'esports.lol': {
						WIN: true,
						SET_WIN: true,
						TOTALS: true,
						SET_TOTALS: true,
						TEAM_TOTALS: true,
						SET_TEAM_TOTALS: true,
						HANDICAP: true,
						SET_HANDICAP: true,
						SET_TOTALS_ODD: false,
						OTHER: false,
					},
					'table-tennis': {
						WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						SET_TOTALS_ODD: false,
						OTHER: false,
						SET_WILL_BE_OT: false,
						SET_TEAMS_TO_SCORE: false,
					},
					'esports.basketball': {
						WIN: false,
						HALF_WIN: false,
						SET_WIN: false,
						WIN_OT: false,
						TOTALS: false,
						HALF_TOTALS: false,
						SET_TOTALS: false,
						TEAM_TOTALS: false,
						HALF_TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						HANDICAP_OT: false,
						HALF_HANDICAP: false,
						SET_HANDICAP: false,
						CORRECT_SCORE: false,
						HALF_TOTALS_ODD: false,
						SET_TOTALS_ODD: false,
						TOTALS_ODD: false,
						OTHER: false,
						TOTALS_OT: false,
						TEAM_GOALS: false,
						SET_TOTALS_3W: false,
						HALF_TOTALS_3W: false,
						SET_TEAM_GOALS: false,
						TEAM_TOTALS_OT: false,
						HALF_TEAM_GOALS: false,
					},
					'esports.hockey': {
						WIN: false,
						WIN_OT: false,
						WIN_RT: false,
						SET_WIN: false,
						TOTALS: false,
						ASIAN_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						SET_TOTALS: false,
						TEAM_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						HANDICAP_RT: false,
						HANDICAP_OT: false,
						CORRECT_SCORE: false,
						TEAMS_TO_SCORE: false,
						OTHER: false,
						TOTALS_OT: false,
						TOTALS_RT: false,
						TEAM_GOALS: false,
						SET_TEAM_GOALS: false,
						ALL_TEAMS_GOALS: false,
						SET_TEAMS_TO_SCORE: false,
						SET_ALL_TEAMS_GOALS: false,
					},
					'esports.tennis': {
						WIN: false,
						SET_WIN: false,
						TOTALS: false,
						SET_TOTALS: false,
						SET_ASIAN_TOTALS: false,
						SET_TEAM_TOTALS: false,
						HANDICAP: false,
						SET_HANDICAP: false,
						GAME_WIN: false,
						SET_TOTALS_ODD: false,
						OTHER: false,
						SET_WILL_BE_OT: false,
						SET_TEAMS_TO_SCORE: false,
					},
				},
				filtersBySport: {
					basketball: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					baseball: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					badminton: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.soccer': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.basketball': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.cs': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.dota2': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.starcraft': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.hockey': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.kog': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.lol': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.overwatch': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.rl': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'esports.tennis': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					floorball: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					futsal: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					handball: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1.5,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					hockey: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 0.75,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'horse-racing': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					rugby: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 1,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					soccer: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 0.5,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					tennis: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 0.5,
						specialFilters: ['GAME_13_OR_11', 'CURRENT_GAME', 'FLOAT_GAME'],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					'table-tennis': {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					volleyball: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
					esports: {
						betOnlyInBreak: false,
						minCorridorParamDiff: 0,
						maxCorridorParamDiff: 2.5,
						specialFilters: [],
						skipIfFirstMarketBasis2: [],
						skipIfLessSecondsUntilEnd: 0,
						skipIfInitiator: [],
						skipIfIntTotalWithSameParams: false,
						skipIfIntHandicapWithSameParams: false,
						betRuleProfit: [1, 30],
						betRuleProfitFollowCommon: true,
						betRuleCoef: [1, 8],
						betRuleCoefFollowCommon: true,
						betRuleLifetime: [0, 2],
						betRuleLifetimeFollowCommon: true,
						forksParsersTypes: ['abb', 'oddscp'],
						forksParsersTypesFollowCommon: true,
						skipIfFirstMarketBasis: [],
					},
				},
				isBlackWhitelistEnabled: false,
				isWhitelistMode: false,
				blackListLeagues: [],
				blackListTeams: [],
				betOnlyInBreak: {
					soccer: false,
					tennis: false,
					hockey: false,
					basketball: false,
					'table-tennis': false,
					baseball: false,
					volleyball: false,
					badminton: false,
					futsal: false,
					handball: false,
					rugby: false,
					'esports.soccer': false,
					'esports.basketball': false,
					'esports.hockey': false,
					'esports.tennis': false,
					esports: false,
				},
			},
			botSettingsBk: {
				bet365: {
					siteUrl: 'https://www.bet365.com',
					isApiBackend: true,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: false,
					notificateIfBetMaxLower: 0,
					notificateAfterBetsCount: 0,
					notificateIfBalanceLower: 0,
					notificateIfBalanceHigher: 0,
					stopBotAfterNonOverlapBets: 0,
					isLandscapeMobileBrowser: true,
				},
				fonbet: {
					siteUrl: 'https://www.fon.bet',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: true,
					notificateIfBetMaxLower: 0,
					notificateAfterBetsCount: 0,
					notificateIfBalanceLower: 0,
					notificateIfBalanceHigher: 0,
					stopBotAfterNonOverlapBets: 0,
					isLandscapeMobileBrowser: true,
				},
				pinnacle: {
					siteUrl: 'https://www.pinnacle.com',
					isApiBackend: true,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'USD',
					incomeDistribution: 0,
					betAmount: [0, 500],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 4,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 1,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: true,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: false,
					notificateIfBetMaxLower: 0,
					notificateAfterBetsCount: 0,
					notificateIfBalanceLower: 0,
					notificateIfBalanceHigher: 0,
					stopBotAfterNonOverlapBets: 0,
					isLandscapeMobileBrowser: true,
				},
				'888sport': {
					siteUrl: 'https://www.888sport.com',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: false,
					notificateIfBetMaxLower: 0,
					notificateAfterBetsCount: 0,
					notificateIfBalanceLower: 0,
					notificateIfBalanceHigher: 0,
					stopBotAfterNonOverlapBets: 0,
					isLandscapeMobileBrowser: true,
				},
				sbobet: {
					siteUrl: 'https://sbobet.com',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: false,
					stopBotAfterNonOverlapBets: 0,
					notificateIfBalanceHigher: 0,
					notificateIfBalanceLower: 0,
					notificateAfterBetsCount: 0,
					notificateIfBetMaxLower: 0,
					isLandscapeMobileBrowser: true,
				},
				'1xbet': {
					siteUrl: 'https://1xstavka.ru',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: true,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isPossibleTSYPIS: true,
					isLandscapeMobileBrowser: true,
				},
				stake: {
					siteUrl: 'https://stake.com',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'USD',
					incomeDistribution: 0,
					betAmount: [5, 5],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 4,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 1,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'pt-BR',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
				},
				parimatch_com: {
					siteUrl: 'https://parimatch.com',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isLandscapeMobileBrowser: true,
				},
				olimp: {
					siteUrl: 'https://www.olimp.bet',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isLandscapeMobileBrowser: true,
				},
				bet9ja: {
					siteUrl: 'https://sports.bet9ja.com',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					refreshBrowserEverySeconds: 0,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
					isLandscapeMobileBrowser: true,
				},
				bingoboom: {
					siteUrl: 'https://bingoboom.ru',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
				},
				zenit: {
					siteUrl: 'https://zenit.win',
					isApiBackend: false,
					shouldUseMobileBrowser: false,
					isNarrowMobileScreen: true,
					isIosMobileBrowser: false,
					isPauseOnRestricted: false,
					currency: 'RUB',
					incomeDistribution: 0,
					betAmount: [0, 10],
					betMaxAmountExceedOnOverlapPercent: 25,
					isBetAmoutInPercent: false,
					betPercentIncludingInPlayBets: false,
					isRoundBet: true,
					roundBetDigits: 0,
					additionalBetsAtSameEvent: 2,
					rebetsAtSameEvent: 0,
					rebetsAtSameEventMarket: 1,
					rebetsAtSameEventMarketGroup: 2,
					bkBetRuleCoef: [1, 8],
					isBkBetRuleFollowedCommon: true,
					ignoreIfMaxBetBelowAmount: 1000,
					isIgnoreIfMaxBetBelow: false,
					browserIsOptimizeMode: false,
					browserLang: 'en',
					browserTz: 'PUBLIC_TZ',
					webRTCPolitic: 'SHOW_PUBLIC_IP',
					webRTCIp: '',
					orderRuleList2: [
						{
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR1_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
							id: 1,
						},
					],
					anonLevel: 2,
					shouldWorkWithoutAuth: false,
					isQrCodeAutoSolveEnabled: false,
					isPossibleApi: false,
					isSiteTSYPIS: false,
					browserIsRandomizedFp: false,
					orderRuleList: [
						{
							id: 1,
							rule: {
								type: 'FORCE_BET_FIRST',
								sports: [],
								marketBasisTypes: ['PLR_TOTAL_OVER', 'TOTAL_OVER'],
							},
							isEnabled: false,
						},
					],
				},
			},
			botSettingsCommon: {
				_loadingCounter: 0,
				browserPath:
					'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
				forksParsersTypes: ['abb', 'oddscp'],
				customForksProviderUrl: 'wss://domain.zone/',
				captchaSolverKey: '',
				isCaptchaSolverEnabled: false,
				isAlternativeBrowserDesign: false,
				forksMarketQrApiKey: '',
				bettingCoQrApiKey: '',
				qrCodeSolverProvider: 'off',
				baseCurrency: 'USD',
				ratesLastUpdatedAt: 1687726050,
				updateRatesAtAppStart: true,
				isBrowserShouldCloseOnBotStop: true,
				currencyRates: {
					RUB: 0.011893533842455872,
					USD: 1,
					EUR: 1.088178659907968,
					UAH: 0.02707705701641189,
					PLN: 0.2461473870500825,
					KZT: 0.002234033822831541,
					BYN: 0.3345603495747467,
					GBP: 1.2737998532337924,
					AMD: 0.0025833112311829426,
					AUD: 0.6696999142476209,
					AZN: 0.5882351541937194,
					MDL: 0.05541982390433793,
					CAD: 0.7598778771945056,
					SEK: 0.09357071241078362,
					BRL: 0.2094368054919582,
					INR: 0.0012212518420110538,
				},
				automationRuleList: [
					{
						rule: {
							eventType: 'BOT_STOPPED',
							actionList: [
								{
									type: 'SEND_NOTIFICATION',
									params: { souceList: ['TELEGRAM'] },
								},
							],
							eventParams: {},
							extraOptions: { onlyForBookmakers: [] },
						},
						isEnabled: true,
					},
					{
						rule: {
							eventType: 'BK_LOGOUT',
							eventParams: {},
							actionList: [
								{ type: 'STOP_BOT', params: {} },
								{
									type: 'OPEN_URL',
									params: {
										url: 'http://node-br-5.astroproxy.com:10273/api/changeIP?apiToken=940d5c8f3a2fdd6a',
									},
								},
							],
							extraOptions: { onlyForBookmakers: [] },
						},
						isEnabled: false,
					},
					{
						isEnabled: true,
						rule: {
							eventType: 'SUCCESS_FORK',
							eventParams: {},
							actionList: [
								{ type: 'PAUSE_BOT', params: {} },
								{
									type: 'SEND_NOTIFICATION',
									params: { souceList: ['TELEGRAM'] },
								},
							],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: true,
						rule: {
							eventType: 'SESSION_TIME_TICK_NO_BETS',
							eventParams: { seconds: 600 },
							actionList: [{ type: 'STOP_BOT', params: {} }],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: false,
						rule: {
							eventType: 'BOT_STOPPED',
							eventParams: {},
							actionList: [{ type: 'START_BOT', params: {} }],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: true,
						rule: {
							eventType: 'BOT_STARTED',
							eventParams: {},
							actionList: [{ type: 'PAUSE_BOT', params: {} }],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: false,
						rule: {
							eventType: 'ACCOUNT_LIMITED',
							eventParams: {},
							actionList: [
								{
									type: 'OPEN_URL',
									params: {
										url: 'https://script.google.com/macros/s/AKfycbzgkCqFJ2cnWMcpi7qa_8bES8Gf6EMTJKARU_zGX1VArvh-qu9HKexB_3af6jdOHoc/exec?botId=247087cd37aa4228a657a29dde7cda67:EE19:9c00d3c12a204f72af387ed2ddef4dd8&serverName=EE №31 (Ethan)&message=ACCOUNT_LIMITED',
									},
								},
								{
									type: 'SEND_NOTIFICATION',
									params: { souceList: ['TELEGRAM'] },
								},
							],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: false,
						rule: {
							eventType: 'ACCOUNT_BANNED',
							eventParams: {},
							actionList: [
								{
									type: 'OPEN_URL',
									params: {
										url: 'https://script.google.com/macros/s/AKfycbzgkCqFJ2cnWMcpi7qa_8bES8Gf6EMTJKARU_zGX1VArvh-qu9HKexB_3af6jdOHoc/exec?botId=247087cd37aa4228a657a29dde7cda67:EE19:9c00d3c12a204f72af387ed2ddef4dd8&serverName=EE №31 (Ethan)&message=ACCOUNT_BANNED',
									},
								},
								{
									type: 'SEND_NOTIFICATION',
									params: { souceList: ['TELEGRAM'] },
								},
							],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
					{
						isEnabled: false,
						rule: {
							eventType: 'SUCCESS_FORK',
							eventParams: {},
							actionList: [
								{
									type: 'OPEN_URL',
									params: {
										url: 'https://script.google.com/macros/s/AKfycbzgkCqFJ2cnWMcpi7qa_8bES8Gf6EMTJKARU_zGX1VArvh-qu9HKexB_3af6jdOHoc/exec?botId=247087cd37aa4228a657a29dde7cda67:EE19:9c00d3c12a204f72af387ed2ddef4dd8&serverName=EE №31 (Ethan)&message=SUCCESS_FORK',
									},
								},
								{
									type: 'SEND_NOTIFICATION',
									params: { souceList: ['TELEGRAM'] },
								},
							],
							extraOptions: { onlyForBookmakers: [] },
						},
					},
				],
				notificationBk: ['TELEGRAM'],
				notificationOnStop: ['TELEGRAM'],
				notificationLossBet: ['TELEGRAM'],
				notificationSuccessBet: ['TELEGRAM'],
				notificationNonOverlapBet: ['TELEGRAM'],
			},
		},
	},
}
